language: python
python:
  - "3.6"
addons:
  apt:
    update: true
before_install:
  - pip install pytest-cov
  - pip install codecov
  - pip install pytest-env
  - pip install pyyaml
script: 
  - py.test --cov=app tests/
after_success:
  - codecov